# Generated by Django 3.1.6 on 2021-03-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
