# Generated by Django 3.1.6 on 2021-03-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_profile_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
